services:
  - type: web
    name: odds-notifyer-server
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: ODDS_API_KEY
        sync: false
      - key: ODDS_API_BASE
        value: https://api2.odds-api.io/v3
      - key: MAX_CALLS_PER_HOUR
        value: 5000
      - key: REFRESH_INTERVAL
        value: "*/2 * * * *"
    healthCheckPath: /health
